CREATE TABLE teaching_staff (
    staff_id SERIAL PRIMARY KEY,
    year INT,
    nationality_country VARCHAR(100),
    gender VARCHAR(20),
    birth_year INT,
    staff_type VARCHAR(100),
    rank_category VARCHAR(100),
    contract_type TEXT,
    part_time_hours FLOAT,
    admin_status VARCHAR(100),
    dedication_type TEXT,
    department_id INT,
    department_name TEXT,
    doctorate_code VARCHAR(50),
    doctorate_mention VARCHAR(100),
    european_code VARCHAR(50),
    seniority_periods INT,
    teaching_merit_periods INT,
    research_merit_periods INT,
    thesis_count INT,
    principal_investigator BOOLEAN,
    FOREIGN KEY (department_id) REFERENCES department(department_id)
);

INSERT INTO teaching_staff (
    year,
    nationality_country,
    gender,
    birth_year,
    staff_type,
    rank_category,
    contract_type,
    part_time_hours,
    admin_status,
    dedication_type,
    department_id,
    department_name,
    doctorate_code,
    european_code,
    seniority_periods,
    teaching_merit_periods,
    research_merit_periods,
    thesis_count,
    principal_investigator
)
SELECT
    anio AS year,
    des_pais_nacionalidad AS nationality_country,
    des_genero AS gender,
    anio_nacimiento AS birth_year,
    des_tipo_personal AS staff_type,
    des_categoria_cuerpo_escala AS rank_category,
    des_tipo_contrato AS contract_type,
    num_horas_semanales_tiempo_parcial AS part_time_hours,
    des_situacion_administrativa AS admin_status,
    des_dedicacion AS dedication_type,
    cod_unidad_responsable AS department_id,
    des_unidad_responsable AS department_name,
    cod_titulo_doctorado AS doctorate_code,
    cod_mencion_europea_int AS european_code,
    num_trienios AS seniority_periods,
    num_quinquenios AS teaching_merit_periods,
    num_sexenios AS research_merit_periods,
    num_tesis AS thesis_count,
    ind_investigador_principal AS principal_investigator
FROM raw_teaching_staff;